ci 178

diff --git a/.github/workflows/mobilecoin-test.yaml b/.github/workflows/mobilecoin-test.yaml
--- a/.github/workflows/mobilecoin-test.yaml
+++ b/.github/workflows/mobilecoin-test.yaml
@@ -46,11 +46,11 @@ jobs:
 
     - name: Check cache successful
       env:
-        BIN_CACHE: ${{ steps.artifact_cache.outputs.cache-hit }}
-        SAMPLE_DATA_CACHE: ${{ steps.sample_data.outputs.cache-hit }}
+        BIN_CACHE: "${{ steps.artifact_cache.outputs.cache-hit }}"
+        SAMPLE_DATA_CACHE: "${{ steps.sample_data_cache.outputs.cache-hit }}"
       run: |
-        if [ "BIN_CACHE" != "true" ]; then echo "Binary cache not found. Start over from build."; exit 1; fi
-        if [ "SAMPLE_DATA_CACHE" != "true" ]; then echo "Sample data cache not found. Start over from build."; exit 1; fi
+        if [ "BIN_CACHE" == "false" ]; then echo "Binary cache not found. Start over from build."; exit 1; fi
+        if [ "SAMPLE_DATA_CACHE" == "false" ]; then echo "Sample data cache not found. Start over from build."; exit 1; fi
 
     - name: Distribute coins to fog accounts
       env:
@@ -97,8 +97,8 @@ jobs:
         BIN_CACHE: ${{ steps.artifact_cache.outputs.cache-hit }}
         SAMPLE_DATA_CACHE: ${{ steps.sample_data.outputs.cache-hit }}
       run: |
-        if [ "BIN_CACHE" != "true" ]; then echo "Binary cache not found. Start over from build."; exit 1; fi
-        if [ "SAMPLE_DATA_CACHE" != "true" ]; then echo "Sample data cache not found. Start over from build."; exit 1; fi
+        if [ "BIN_CACHE" == "false" ]; then echo "Binary cache not found. Start over from build."; exit 1; fi
+        if [ "SAMPLE_DATA_CACHE" == "false" ]; then echo "Sample data cache not found. Start over from build."; exit 1; fi
 
     - name: Run fog-test-client
       env:
