ci 212 [skip-build] [skip-docker] [skip-charts] [skip-reset] [skip-sample-data] [skip-deploy] [skip-test-distribute-fog-accounts] [skip-test-fog-test-client]

diff --git a/.github/workflows/mobilecoin-test.yaml b/.github/workflows/mobilecoin-test.yaml
--- a/.github/workflows/mobilecoin-test.yaml
+++ b/.github/workflows/mobilecoin-test.yaml
@@ -17,6 +17,7 @@ jobs:
         echo namespace ${{ github.event.inputs.namespace }}
 
   distribute-fog-accounts:
+    if: "! contains(toJSON(github.event.commits.*.message), '[skip-test-distribute-fog-accounts]')"
     runs-on: self-hosted
     steps:
     - name: Start with clean workspace
@@ -63,6 +64,10 @@ jobs:
           --num-tx-to-send 20
 
   fog-test-client:
+    if: |
+      always() &&
+      ! contains(toJSON(github.event.commits.*.message), '[skip-test-fog-test-client]') &&
+      (needs.distribute-fog-accounts.result == 'success' || needs.distribute-fog-accounts.result == 'skipped')
     runs-on: self-hosted
     needs:
     - distribute-fog-accounts
@@ -97,8 +102,15 @@ jobs:
         BIN_CACHE: ${{ steps.artifact_cache.outputs.cache-hit }}
         SAMPLE_DATA_CACHE: ${{ steps.sample_data.outputs.cache-hit }}
       run: |
-        if [ "BIN_CACHE" == "false" ]; then echo "Binary cache not found. Start over from build."; exit 1; fi
-        if [ "SAMPLE_DATA_CACHE" == "false" ]; then echo "Sample data cache not found. Start over from build."; exit 1; fi
+        if [ "${BIN_CACHE}" == "false" ]
+        then
+          echo "Binary cache not found. Start over from build."; exit 1
+        fi
+
+        if [ "${SAMPLE_DATA_CACHE}" == "false" ]
+        then
+          echo "Sample data cache not found. Start over from build."; exit 1
+        fi
 
     - name: Run fog-test-client
       env:
@@ -117,6 +129,10 @@ jobs:
           --fog-ledger fog-ledger://fog.${NAMESPACE}.development.mobilecoin.com:443
 
   mobilecoind-integration:
+    if: |
+      always() &&
+      ! contains(toJSON(github.event.commits.*.message), '[skip-test-mobilecoind-integration]') &&
+      (needs.distribute-fog-accounts.result == 'success' || needs.distribute-fog-accounts.result == 'skipped')
     runs-on: self-hosted
     container:
       image: python:3
@@ -130,7 +146,6 @@ jobs:
       uses: actions/checkout@v2
 
     - name: Cache sample_data
-      if: steps.artifact_cache.outputs.cache-hit == 'true'
       id: sample_data_cache
       uses: actions/cache@v2
       with:
@@ -140,11 +155,12 @@ jobs:
 
     - name: Check cache successful
       env:
-        BIN_CACHE: ${{ steps.artifact_cache.outputs.cache-hit }}
         SAMPLE_DATA_CACHE: ${{ steps.sample_data.outputs.cache-hit }}
       run: |
-        if [ "BIN_CACHE" == "false" ]; then echo "Binary cache not found. Start over from build."; exit 1; fi
-        if [ "SAMPLE_DATA_CACHE" == "false" ]; then echo "Sample data cache not found. Start over from build."; exit 1; fi
+        if [ "${SAMPLE_DATA_CACHE}" == "false" ]
+        then
+          echo "Sample data cache not found. Start over from build."; exit 1
+        fi
 
     - name: Run wallet integration (mobilecoind) tests
       env:
